---
title: "Formative Scenario Analysis Exercise"
author: "Tobias, Dario"
date: "26 2 2019"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

if(!require("knitr")){
  install.packages("knitr")
  require("knitr")
}
if(!require("tidyverse")){
  install.packages("tidyverse")
  require("tidyverse")
}
if(!require("openxlsx")){
  install.packages("openxlsx")
  require("openxlsx")
}


source("../../util/functions.R")

```



## System boundaries
  
- Spatial reference: Europe
- Time reference: 2019 - 2050
- Substantial reference: E-Bikes

## Selected impact factors

```{r finalIF, echo=FALSE}
finalmpactFactors <-  read.excel(file = "../../data/exerciseData.xlsx", sheetName = "preliminaryImpactFactors")
finalmpactFactorsList <- as.character(finalmpactFactors$ImpactFactor)
cols <- 3
nrowPerCol <- ceiling(length(finalmpactFactorsList)/cols)
impFac <- c(finalmpactFactorsList, rep("", each = cols * nrowPerCol - length(finalmpactFactorsList)))
impFacTab <- cbind(impFac[1:nrowPerCol], impFac[(nrowPerCol+1):(2*nrowPerCol)], impFac[(2*nrowPerCol+1):(3*nrowPerCol)])
kable(impFacTab)

```

## 2.2 Impact assessment
direct impacts matrix

```{r impactMatrix, echo=FALSE, warning=FALSE}

impactMatrix <- read.excel(file = "../../data/exerciseData.xlsx", sheetName = "impactMatrix")

names(impactMatrix)[1] <- "ImpactFactor"
impactMatrixPlot <- impactMatrix %>% 
  gather(Dependend, value, -ImpactFactor) %>% 
  mutate(value = factor(value)) %>% 
  mutate(value = factor(value),
         ImpactFactor = factor(ImpactFactor),
         ImpactFactor = factor(ImpactFactor, levels = rev(levels(ImpactFactor)))) %>%
  filter(!is.na(value)) %>% 
  ggplot(aes(Dependend, ImpactFactor, fill=value)) +
  geom_tile() +
  scale_fill_manual(values = c("0" = mc(5), "1" = mc(4),"2" = mc(1)), na.value=mc(7)) +
  geom_text(aes(label = value)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


impactMatrixPlot

```


## System grid
```{r plotSystemGrid, echo=FALSE}
impactM <- read.excel(file = "../../data/exerciseData.xlsx", sheetName = "impactMatrix")
rownames(impactM) <- impactM[,1]
impactM <- impactM[,-1]
impactM$ActivityScore <- rowSums(impactM, na.rm = TRUE)
PassivityScore <- colSums(impactM, na.rm = TRUE)
impactM <- rbind.data.frame(impactM, PassivityScore= PassivityScore)

sysGridData <- impactM
sysGridData$PassivityScore <- as.numeric(t(sysGridData[nrow(sysGridData),]))
sysGridData$ImpactFactor <- rownames(sysGridData)
sysGridData <- sysGridData %>%
  select(ImpactFactor, ActivityScore, PassivityScore) %>%
  filter(!(ImpactFactor %in% c("PassivityScore")))
  
library(ggrepel)

sysGridData %>% 
  ggplot(aes(ActivityScore, PassivityScore, label=ImpactFactor)) +
  geom_point() +
  geom_hline(aes(yintercept = mean(PassivityScore))) +
  geom_vline(aes(xintercept = mean(ActivityScore))) +
  geom_text_repel()


```
